import Foundation

struct MockData {
    static let tasks: [CommanderTask] = [
        CommanderTask(
            id: "task_001",
            numId: 1,
            project: "everbnb",
            path: "~/repos/everbnb-backend",
            task: "Add rate limiting to upload endpoint",
            description: "Add express-rate-limit middleware to the /api/upload endpoint. Set 10 req/min per IP. Return 429 with retry-after header.",
            dependsOn: [],
            status: .running,
            priority: 5,
            assignedWorker: "macbook-pro-1",
            claimedBy: "macbook-pro-1",
            costUsd: 0.47,
            durationMs: 342000,
            exitCode: nil,
            error: nil,
            sessionId: "sess_abc123",
            reviewStatus: .none,
            testStatus: "passing",
            deployStatus: nil,
            followUp: nil,
            createdAt: Date().addingTimeInterval(-600),
            startedAt: Date().addingTimeInterval(-342),
            completedAt: nil
        ),
        CommanderTask(
            id: "task_002",
            numId: 2,
            project: "everbnb",
            path: "~/repos/everbnb-frontend",
            task: "Fix auth redirect loop on expired tokens",
            description: "Users are getting stuck in a redirect loop when their JWT expires. Fix the auth middleware to properly redirect to /login with a flash message.",
            dependsOn: [],
            status: .done,
            priority: 3,
            assignedWorker: nil,
            claimedBy: "mac-mini-1",
            costUsd: 1.23,
            durationMs: 890000,
            exitCode: 0,
            error: nil,
            sessionId: "sess_def456",
            reviewStatus: .needsReview,
            testStatus: "passing",
            deployStatus: "deployed",
            followUp: "**What was done**: Added express-rate-limit middleware to /api/auth with per-IP limiting.\n\n**What needs review**: Verify 401 responses for expired tokens include proper WWW-Authenticate headers.\n\n**Action items**: Check rate limit thresholds match production traffic patterns.",
            createdAt: Date().addingTimeInterval(-7200),
            startedAt: Date().addingTimeInterval(-6000),
            completedAt: Date().addingTimeInterval(-5110)
        ),
        CommanderTask(
            id: "task_003",
            numId: 3,
            project: "gym-app",
            path: "~/repos/gym-app",
            task: "Add member check-in screen",
            description: "Create a new screen where gym members can check in by scanning their QR code or entering their member ID.",
            dependsOn: [],
            status: .pending,
            priority: 10,
            assignedWorker: nil,
            claimedBy: nil,
            costUsd: nil,
            durationMs: nil,
            exitCode: nil,
            error: nil,
            sessionId: nil,
            reviewStatus: .none,
            testStatus: nil,
            deployStatus: nil,
            followUp: nil,
            createdAt: Date().addingTimeInterval(-300),
            startedAt: nil,
            completedAt: nil
        ),
        CommanderTask(
            id: "task_004",
            numId: 4,
            project: "gym-app",
            path: "~/repos/gym-app",
            task: "Fix class booking timezone bug",
            description: "Classes are showing in UTC instead of the gym's local timezone. Fix the booking display to use the gym's configured timezone.",
            dependsOn: [3],
            status: .blocked,
            priority: 8,
            assignedWorker: nil,
            claimedBy: nil,
            costUsd: nil,
            durationMs: nil,
            exitCode: nil,
            error: nil,
            sessionId: nil,
            reviewStatus: .none,
            testStatus: nil,
            deployStatus: nil,
            followUp: nil,
            createdAt: Date().addingTimeInterval(-200),
            startedAt: nil,
            completedAt: nil
        ),
        CommanderTask(
            id: "task_005",
            numId: 5,
            project: "everbnb",
            path: "~/repos/everbnb-backend",
            task: "Migrate user table to add 2FA columns",
            description: "Add two-factor authentication columns (totp_secret, totp_enabled, backup_codes) to the users table with a reversible migration.",
            dependsOn: [1],
            status: .failed,
            priority: 7,
            assignedWorker: "macbook-pro-1",
            claimedBy: "macbook-pro-1",
            costUsd: 0.89,
            durationMs: 456000,
            exitCode: 1,
            error: "Migration failed: column totp_secret already exists",
            sessionId: "sess_ghi789",
            reviewStatus: .none,
            testStatus: "failing",
            deployStatus: nil,
            followUp: nil,
            createdAt: Date().addingTimeInterval(-3600),
            startedAt: Date().addingTimeInterval(-3200),
            completedAt: Date().addingTimeInterval(-2744)
        ),
        CommanderTask(
            id: "task_006",
            numId: 6,
            project: "gym-app",
            path: "~/repos/gym-app",
            task: "Update pricing page copy",
            description: "Update the pricing page to reflect new membership tiers: Basic ($29/mo), Pro ($49/mo), Elite ($79/mo).",
            dependsOn: [],
            status: .done,
            priority: 10,
            assignedWorker: nil,
            claimedBy: "mac-mini-1",
            costUsd: 0.34,
            durationMs: 120000,
            exitCode: 0,
            error: nil,
            sessionId: "sess_jkl012",
            reviewStatus: .approved,
            testStatus: "passing",
            deployStatus: "deployed",
            followUp: "**What was done**: Updated pricing page with new membership tiers.\n\n**What needs review**: Verify copy matches brand voice.\n\n**Action items**: None — deployed successfully.",
            createdAt: Date().addingTimeInterval(-10800),
            startedAt: Date().addingTimeInterval(-10600),
            completedAt: Date().addingTimeInterval(-10480)
        ),
    ]

    static let workers: [CommanderWorker] = [
        CommanderWorker(
            id: "macbook-pro-1",
            hostname: "macbook-pro-1",
            status: .busy,
            activeTaskCount: 1,
            completedTasks: 47,
            maxParallel: 4,
            lastHeartbeat: Date().addingTimeInterval(-30),
            plan: "max",
            quotaRemaining: 0.72,
            rateLimitResetAt: nil,
            isRateLimited: false
        ),
        CommanderWorker(
            id: "mac-mini-1",
            hostname: "mac-mini-1",
            status: .online,
            activeTaskCount: 0,
            completedTasks: 31,
            maxParallel: 4,
            lastHeartbeat: Date().addingTimeInterval(-15),
            plan: "max",
            quotaRemaining: 0.89,
            rateLimitResetAt: nil,
            isRateLimited: false
        ),
        CommanderWorker(
            id: "linux-server-1",
            hostname: "linux-server-1",
            status: .offline,
            activeTaskCount: 0,
            completedTasks: 12,
            maxParallel: 2,
            lastHeartbeat: Date().addingTimeInterval(-3600),
            plan: "pro",
            quotaRemaining: nil,
            rateLimitResetAt: nil,
            isRateLimited: false
        ),
    ]

    static let outputChunks: [OutputChunk] = [
        OutputChunk(id: "out_1", type: .assistant, content: "I'll add rate limiting to the upload endpoint. Let me start by reading the current route handler.", timestamp: Date().addingTimeInterval(-300), order: 1),
        OutputChunk(id: "out_2", type: .toolUse, content: "Read file: src/routes/upload.js", timestamp: Date().addingTimeInterval(-295), order: 2),
        OutputChunk(id: "out_3", type: .toolResult, content: "const router = require('express').Router();\nconst multer = require('multer');\n\nrouter.post('/', upload.single('file'), async (req, res) => {\n  // ... existing upload logic\n});", timestamp: Date().addingTimeInterval(-294), order: 3),
        OutputChunk(id: "out_4", type: .assistant, content: "I can see the upload route. I'll add express-rate-limit middleware. First, let me install the package.", timestamp: Date().addingTimeInterval(-290), order: 4),
        OutputChunk(id: "out_5", type: .toolUse, content: "Bash: npm install express-rate-limit", timestamp: Date().addingTimeInterval(-285), order: 5),
        OutputChunk(id: "out_6", type: .toolResult, content: "added 1 package in 2.1s", timestamp: Date().addingTimeInterval(-283), order: 6),
        OutputChunk(id: "out_7", type: .assistant, content: "Now I'll add the rate limiter configuration to the upload route.", timestamp: Date().addingTimeInterval(-280), order: 7),
    ]

    static let chatMessages: [ChatMessage] = [
        ChatMessage(id: "chat_1", role: .user, content: "Make sure the rate limit applies per-IP, not globally", timestamp: Date().addingTimeInterval(-250), senderName: "James", isPending: false),
        ChatMessage(id: "chat_2", role: .assistant, content: "Good point. I've configured the rate limiter with `keyGenerator: (req) => req.ip` to ensure per-IP limiting.", timestamp: Date().addingTimeInterval(-245), senderName: nil, isPending: false),
    ]

    static let activities: [ActivityEvent] = [
        ActivityEvent(id: "act_1", action: "task_created", details: ["task_num_id": "6", "project": "gym-app", "task_name": "Update pricing page copy"], userEmail: "james@example.com", userName: "James", timestamp: Date().addingTimeInterval(-10800)),
        ActivityEvent(id: "act_2", action: "task_created", details: ["task_num_id": "5", "project": "everbnb", "task_name": "Migrate user table"], userEmail: "james@example.com", userName: "James", timestamp: Date().addingTimeInterval(-3600)),
        ActivityEvent(id: "act_3", action: "task_status_changed", details: ["task_num_id": "5", "new_status": "failed"], userEmail: nil, userName: "System", timestamp: Date().addingTimeInterval(-2744)),
        ActivityEvent(id: "act_4", action: "task_created", details: ["task_num_id": "3", "project": "gym-app", "task_name": "Add member check-in screen"], userEmail: "james@example.com", userName: "James", timestamp: Date().addingTimeInterval(-300)),
        ActivityEvent(id: "act_5", action: "chat_message_sent", details: ["task_num_id": "1", "message_preview": "Make sure the rate limit applies per-IP..."], userEmail: "james@example.com", userName: "James", timestamp: Date().addingTimeInterval(-250)),
        ActivityEvent(id: "act_6", action: "task_retried", details: ["task_num_id": "5", "project": "everbnb"], userEmail: "james@example.com", userName: "James", timestamp: Date().addingTimeInterval(-120)),
    ]

    static let projects: [String] = ["everbnb", "gym-app"]

    static let additionalActivities: [ActivityEvent] = [
        ActivityEvent(id: "act_7", action: "task_approved", details: ["task_num_id": "6", "project": "gym-app"], userEmail: "james@example.com", userName: "James", timestamp: Date().addingTimeInterval(-100)),
        ActivityEvent(id: "act_8", action: "task_status_changed", details: ["task_num_id": "1", "new_status": "running", "project": "everbnb"], userEmail: nil, userName: "System", timestamp: Date().addingTimeInterval(-350)),
        ActivityEvent(id: "act_9", action: "task_status_changed", details: ["task_num_id": "6", "new_status": "done", "project": "gym-app", "task_name": "Update pricing page copy"], userEmail: nil, userName: "System", timestamp: Date().addingTimeInterval(-10480)),
    ]
}
